extension_dir = "D:\php-7.4.32-Win32-vc15-x64\ext"
extension=pdo_sqlite
extension=sqlite3
extension=pdo_mysql
extension=mysqli
extension=mbstring
extension=curl
extension=fileinfo
extension=gd2

date.timezone = Asia/Shanghai
upload_max_filesize = 50M
post_max_size = 50M
memory_limit = 256M
